version: '3.8'

services:
  web:
    container_name: aisa-lubrication-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./aisa.db
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    volumes:
      - ./aisa.db:/app/aisa.db
      - ./public/uploads:/app/public/uploads
    networks:
      - aisa-net

networks:
  aisa-net:
    driver: bridge
